# Generated by Django 3.2.9 on 2022-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
