# Generated by Django 3.2.9 on 2022-03-16 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220316_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='name_of_business',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name of business'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('business_name', models.CharField(max_length=70, verbose_name='Business Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('taxable', models.BooleanField(default=False, verbose_name='Taxable')),
                ('invoice_pref', models.CharField(max_length=15, verbose_name='Invoice Preference')),
                ('logo_path', models.CharField(max_length=150, verbose_name='Logo Path')),
                ('ship_to', models.CharField(max_length=500, verbose_name='Ship to')),
                ('shipping_address', models.CharField(max_length=500, verbose_name='Shipping Address')),
                ('billing_address', models.CharField(max_length=500, verbose_name='Billing Address')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Notes')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
