# Generated by Django 3.2.9 on 2022-03-31 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220329_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sales_tex',
        ),
        migrations.AddField(
            model_name='item',
            name='sales_tax',
            field=models.FloatField(default=0.0, verbose_name='Sales Tax'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.myusers'),
            preserve_default=False,
        ),
    ]
