# Generated by Django 3.2.9 on 2022-04-01 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220331_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('taxable', models.BooleanField(default=False, verbose_name='Taxable')),
                ('quote_pref', models.CharField(max_length=15, verbose_name='Invoice Preference')),
                ('theme', models.CharField(max_length=150, verbose_name='Logo Path')),
                ('quote_number', models.PositiveIntegerField(verbose_name='Quote number')),
                ('quote_date', models.DateField(verbose_name='Quote Date')),
                ('po_number', models.PositiveIntegerField(verbose_name='PO number')),
                ('ship_to', models.CharField(max_length=500, verbose_name='Ship to')),
                ('shipping_address', models.CharField(max_length=500, verbose_name='Shipping Address')),
                ('bill_to', models.CharField(max_length=2048, verbose_name='Bill To')),
                ('billing_address', models.CharField(max_length=500, verbose_name='Billing Address')),
                ('notes', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Notes')),
                ('items_json', models.JSONField(default=dict, verbose_name='Items Json')),
                ('item_total', models.FloatField(verbose_name='Item Total')),
                ('tax', models.FloatField(blank=True, null=True, verbose_name='Tax')),
                ('add_charges', models.FloatField(blank=True, null=True, verbose_name='Additional Charges')),
                ('grand_total', models.FloatField(verbose_name='Grand Total')),
                ('status', models.CharField(blank=True, default='New', max_length=20, null=True, verbose_name='Status')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
