# Generated by Django 3.2.9 on 2022-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220316_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='customer',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Invoice Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, default='New', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
