# Generated by Django 3.2.9 on 2022-03-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220317_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Username'),
        ),
    ]
