# Generated by Django 3.2.9 on 2022-04-01 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='theme',
            new_name='logo_path',
        ),
        migrations.RenameField(
            model_name='proformainvoice',
            old_name='theme',
            new_name='logo_path',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='theme',
            new_name='logo_path',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='theme',
            new_name='logo_path',
        ),
    ]
