# Generated by Django 3.2.9 on 2022-04-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220401_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=1024, verbose_name='Payment Type')),
                ('paid_date', models.DateField(verbose_name='Paid Date')),
                ('paid_amount', models.FloatField(verbose_name='Paid Amount')),
                ('payment_method', models.CharField(max_length=1024, verbose_name='Payment Method')),
                ('reference', models.CharField(max_length=1024, verbose_name='Reference')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quote')),
            ],
        ),
    ]
