# Generated by Django 3.2.9 on 2022-04-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_deliverynote_paydeliverynote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myusers',
            old_name='name_of_business',
            new_name='business_name',
        ),
        migrations.AddField(
            model_name='myusers',
            name='bank_transer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Trnasfer'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='business_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Number'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='currency',
            field=models.CharField(default='Dollar', max_length=24, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='e_transfer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-Transfer'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='email_report',
            field=models.CharField(default='Monthly', max_length=100, verbose_name='Email Reports'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='fax',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='lang_pref',
            field=models.CharField(default='English', max_length=50, verbose_name='Language Preference'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='other_payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Other Payment'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='other_phone_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Other phone number'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='paypal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayPal'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='phon_number_type',
            field=models.CharField(default='Mobile', max_length=24, verbose_name='Type of phone number'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='region',
            field=models.CharField(default='US', max_length=100, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='tax_rate',
            field=models.FloatField(default=0.0, verbose_name='Tax Rate'),
        ),
        migrations.AddField(
            model_name='myusers',
            name='tax_type',
            field=models.CharField(default='On Total', max_length=24, verbose_name='Tax Type'),
        ),
    ]
