# Generated by Django 3.2.9 on 2022-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220404_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='photo_path',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Profile Photo Path'),
        ),
    ]
