# Generated by Django 3.2.9 on 2022-04-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_myusers_photo_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myusers',
            old_name='phon_number_type',
            new_name='phone_number_type',
        ),
    ]
