# Generated by Django 3.2.9 on 2022-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_phon_number_type_myusers_phone_number_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='logo_path',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Logo Path'),
        ),
    ]
