# Generated by Django 3.2.9 on 2022-04-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_myusers_logo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=2048, null=True, verbose_name='Address'),
        ),
    ]
