# Generated by Django 3.2.9 on 2022-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_myusers_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='bank_transer',
        ),
        migrations.AddField(
            model_name='myusers',
            name='bank_tranfser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Transfer'),
        ),
    ]
