# Generated by Django 3.2.9 on 2022-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220404_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='bank_tranfser',
        ),
        migrations.AddField(
            model_name='myusers',
            name='bank_transfer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Transfer'),
        ),
    ]
