# Generated by Django 3.2.9 on 2022-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220410_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='items_json',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='items_json',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='items_list',
            field=models.CharField(default='1', max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='items_list',
            field=models.CharField(default='1', max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='items_list',
            field=models.CharField(default=1, max_length=1024, verbose_name='Items List'),
            preserve_default=False,
        ),
    ]
