# Generated by Django 3.2.9 on 2022-04-12 17:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220412_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='items_list',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='items_list',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='estimate',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='quote',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='receipt',
            name='item_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
    ]
