# Generated by Django 3.2.9 on 2022-04-12 19:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_invoice_quantity_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='estimate',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='quote',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='receipt',
            name='quantity_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True), default=list, size=None),
        ),
    ]
