# Generated by Django 3.2.9 on 2022-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220412_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
