# Generated by Django 3.2.9 on 2022-04-19 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220419_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 14, 11, 4, 335008), verbose_name='Due Date'),
        ),
    ]
