# Generated by Django 3.2.9 on 2022-04-19 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_purchaseorder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='address',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='address',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='address',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 19, 17, 39, 50, 333799), verbose_name='Due Date'),
        ),
    ]
