# Generated by Django 3.2.9 on 2022-04-20 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220420_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 20, 11, 42, 22, 450542), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 20, 11, 42, 22, 447541), verbose_name='Due Date'),
        ),
    ]
