# Generated by Django 3.2.9 on 2022-04-22 09:09

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220420_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='photo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 10, 9, 52, 959066), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 10, 9, 52, 961020), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='logo_path',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Logo photo'),
        ),
    ]
