# Generated by Django 3.2.9 on 2022-04-23 11:05

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220422_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 12, 5, 13, 90703), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 12, 5, 13, 91703), verbose_name='Due Date'),
        ),
    ]
