# Generated by Django 3.2.9 on 2022-04-23 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220423_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='proformainvoice',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='logo_path',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 13, 8, 1, 487133), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 13, 8, 1, 488133), verbose_name='Due Date'),
        ),
    ]
