# Generated by Django 3.2.9 on 2022-04-23 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220423_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 12, 9, 27, 836694, tzinfo=utc), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 23, 12, 9, 27, 837693, tzinfo=utc), verbose_name='Due Date'),
        ),
    ]
