# Generated by Django 3.2.9 on 2022-04-24 10:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220423_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='paycreditnote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paycreditnote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='paydeliverynote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paydeliverynote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='payestimate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payestimate',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='payinvoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payinvoice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='payproforma',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payproforma',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='paypurchaseorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paypurchaseorder',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='payquote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payquote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='payreceipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payreceipt',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date modified'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 10, 46, 15, 617091, tzinfo=utc), verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 10, 46, 15, 618091, tzinfo=utc), verbose_name='Due Date'),
        ),
    ]
