# Generated by Django 3.2.9 on 2022-04-24 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220424_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
    ]
