# Generated by Django 3.2.9 on 2022-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220424_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='currency',
            field=models.CharField(blank=True, default='Dollar', max_length=24, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email_report',
            field=models.CharField(blank=True, default='Monthly', max_length=100, null=True, verbose_name='Email Reports'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='lang_pref',
            field=models.CharField(blank=True, default='English', max_length=50, null=True, verbose_name='Language Preference'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='region',
            field=models.CharField(blank=True, default='US', max_length=100, null=True, verbose_name='Region'),
        ),
    ]
