# Generated by Django 3.2.9 on 2022-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_item_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
