# Generated by Django 3.2.9 on 2022-04-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20220426_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sales_tax',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sales Tax'),
        ),
    ]
