# Generated by Django 3.2.9 on 2022-04-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_item_sales_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='invoice_number',
        ),
    ]
