# Generated by Django 3.2.9 on 2022-04-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_myusers_password_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='password_recovery_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
