# Generated by Django 3.2.9 on 2022-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_myusers_password_recovery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='password_recovery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
