# Generated by Django 3.2.9 on 2022-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_myusers_password_recovery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='po_number',
            field=models.CharField(blank=True, default=1, max_length=1024, null=True, verbose_name='PO Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Invoice number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
    ]
