# Generated by Django 3.2.9 on 2022-05-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20220501_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(error_messages={'blank': 'Invoice date is required'}, verbose_name='Invoice Date'),
        ),
    ]
