# Generated by Django 3.2.9 on 2022-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='emailed_date',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='bill_to',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Bill To'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bill_to',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Bill To'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='bill_to',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Bill To'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='bill_to',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Bill To'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='billing_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='ship_to',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ship to'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Shipping Address'),
        ),
    ]
