# Generated by Django 3.2.9 on 2022-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20220505_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estimate',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='receipt',
            name='recurring_data',
            field=models.JSONField(default=dict),
        ),
    ]
