# Generated by Django 3.2.9 on 2022-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_pdftemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='name',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Name'),
        ),
    ]
