# Generated by Django 3.2.9 on 2022-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_pdftemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='proformainvoice',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='add_charges',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Additional Charges'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax',
            field=models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Tax'),
        ),
    ]
