# Generated by Django 3.2.9 on 2022-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20220521_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformainvoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='PO number'),
        ),
    ]
