# Generated by Django 3.2.9 on 2022-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220528_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Username'),
        ),
    ]
