# Generated by Django 3.2.9 on 2022-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='terms',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Terms'),
        ),
    ]
