# Generated by Django 3.2.9 on 2022-06-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_customer_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill_to',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Bill to'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pdf_template',
            field=models.CharField(blank=True, default='Clapbill 1', max_length=64, null=True, verbose_name='PDF Template Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number_type',
            field=models.CharField(blank=True, default='Mobile', max_length=64, null=True, verbose_name='Phone Number Type'),
        ),
    ]
