# Generated by Django 3.2.9 on 2022-06-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_auto_20220602_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='logo_path',
            new_name='logo',
        ),
    ]
