# Generated by Django 3.2.9 on 2022-06-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_rename_logo_path_customer_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdftemplate',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='myusers',
            name='currency',
            field=models.CharField(blank=True, default='NGN', max_length=24, null=True, verbose_name='Currency'),
        ),
    ]
