# Generated by Django 3.2.9 on 2022-06-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_inbuiltlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbuiltlogo',
            name='category',
            field=models.CharField(default=None, max_length=1024, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
