# Generated by Django 3.2.9 on 2022-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
